# ~/.config/starship.toml

right_format = """$cmd_duration$battery$aws"""

add_newline = true
format = """
 [ ó°Š   ](bold italic #FFA500) \ 
 [](bg:#769ff0 fg:#769ff0)$directory\
 [](bold italic skyblue)$git_branch$python$golang$nodejs 
 [\n ï–´ ](#00FFFF)$character
"""
# ~/.config/starship.toml
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾  "

"Desktop" = "ï‰¬  "
"~" = "î˜— "
"nvim" = "î˜«"
".config" = "ó°´³ "


[git_branch]
symbol = 'ï˜ '
truncation_length = 8
truncation_symbol = '..'
format = 'on âŒ  [$symbol$branch(:$remote_branch) ]($style)âŒ¡  '
style = "bold green"

[golang]
symbol = 'ó°Ÿ“  '
format = 'via [$symbol($version )]($style)'


#
# # Replace the "â¯"
[character]
success_symbol = "[ó°‹‡ ](#00FFFF)"
error_symbol = "[ó°’² ](red)"
#
# # configure directory
[directory]
read_only = " ï ½"
format = "[ îƒ‡](#2687A2)[ $path]($style)[$lock_symbol]($lock_style )[îƒ€ ](bold #2687A2) "
truncation_length = 10
truncate_to_repo = true                                                                 # truncates directory to root folder if in github repo
style = "italic fg:#e3e5e5 bg:#2687A2"
#
[os]
format = " ($style)"
style = "bold blue italic"
disabled = false


#
[cmd_duration]
min_time = 4
show_milliseconds = false
format = 'ó°ª¢ [$duration]($style) '
disabled = false
style = "bold italic blue"
#
#
[python]
symbol = "ó±” "
#pyenv_version_name = true
format = 'via [${symbol}(${version}) â¥‹ (\($virtualenv\))]($style) '
style = "bold  #00C5FF"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${major}.${minor}"
#
#
# [nodejs] 
# format = "via [ï¢˜ $version](bold italic green) "
# detect_files = ["package.json", ".node-version"]
# detect_folders = ["node_modules"]
#
#
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = 'ó°…Ÿ '
style = "yellow"
#
#
# [battery]
# full_symbol = "ğŸ”‹"
# charging_symbol = "ğŸ”Œ"
# discharging_symbol = "âš¡"
#
[[battery.display]]
threshold = 30
style = "bold red"
