# ~/.config/starship.toml

right_format = """$cmd_duration$battery$aws"""

add_newline = true 
format = """
 [ Û∞ä†  ](bold italic #FFA500) ‚å† $directory‚å° $git_branch$python$golang$nodejs
 [    ](bold italic skyblue) 
 [ Ôñ¥ ](#00FFFF)$character
"""
# ~/.config/starship.toml

[git_branch]
symbol = 'Ôêò '
truncation_length = 8
truncation_symbol = '..'
format = 'on ‚å† [$symbol$branch(:$remote_branch) ]($style)‚å°  '
style="bold green"

[golang]
symbol = 'Û∞üì  '
format = 'via [$symbol($version )]($style)'


#
# # Replace the "‚ùØ"
[character]
success_symbol = "[Û∞ãá ](#00FFFF)"
error_symbol = "[Û∞í≤ ](red)"
#
# # configure directory
[directory]
read_only = " Ô†Ω"
format = "[$path]($style)[$lock_symbol]($lock_style) "
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "italic #45b3e0"
#
#
[os]
format = " ($style)"
style = "bold blue italic"
disabled = false


#
[cmd_duration]
min_time = 4
show_milliseconds = false
format = 'Û∞™¢ [$duration]($style) '
disabled = false
style = "bold italic blue"
#
#
[python]
symbol = "Û±îé "
#pyenv_version_name = true
format = 'via [${symbol}(${version}) ‚•ã (\($virtualenv\))]($style) '
style = "bold  #00C5FF"
pyenv_prefix = "venv "
python_binary = ["./venv/bin/python", "python", "python3", "python2"]
detect_extensions = ["py"]
version_format = "v${major}.${minor}"
#
#
# [nodejs] 
# format = "via [Ô¢ò $version](bold italic green) "
# detect_files = ["package.json", ".node-version"]
# detect_folders = ["node_modules"]
#
#
[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'
symbol = 'Û∞Öü '
style = "yellow"
#
#
# [battery]
# full_symbol = "üîã"
# charging_symbol = "üîå"
# discharging_symbol = "‚ö°"
#
[[battery.display]]
threshold = 30
style = "bold red"
